name: Lisp application

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: do-testing-should-success
        env:
          STING_SYSTEMS: yolo
        uses: docker://letrov/sting:test
      - name: do-testing-should-fail
        uses: docker://letrov/sting:test
      - name: should-not-run
        run: |
          echo "HELLO WORLD"
