name: Lisp application

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
    steps:
      - uses: actions/checkout@v1
      - name: Hello
        run: echo Hello world
      - name: Container inspection
        run: ls -la ; pwd ; ls / ; which sting
      - name: test-nothing
        env:
          STING_SYSTEMS: :alexandria
        run: sting
