name: Lisp application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
    steps:
      - uses: actions/checkout@v1
      - name: Make system visible by ASDF
        run: ln -s ${GITHUB_WORKSPACE} ${ASDF_PATH}/user-repo
      - name: sting
        env:
          STING_SYSTEMS: :mymath/tests
          HOME: /
        run: sting
