name: Lisp application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:latest
    steps:
      - uses: actions/checkout@v1
      - name: Make system visible by ASDF
        run: ln -s ${GITHUB_WORKSPACE} ${ASDF_PATH}/$(basename ${CI_PROJECT_DIR})
      - name: Run test suite
        env:
          STING_SYSTEMS: :mymath/tests
          HOME: / # override GH Actions' default value (ASDF uses it, default=/github/home)
        run: sting
