name: Lisp application

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Hello
        run: echo Hello world
      - name: Container inspection
        run: ls -Rla ~
      - name: test-nothing
        env:
          STING_SYSTEMS: :alexandria
        run: sting
