name: Lisp application

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
    steps:
      - uses: actions/checkout@v1
      - name: Container inspection
        run: whoami ; ls -la /root ; ls -la /root/quicklisp
      - name: test-nothing
        env:
          STING_SYSTEMS: :alexandria
          HOME: /root
        run: sting
