name: Lisp application

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
    steps:
      - uses: actions/checkout@v1
      - name: Container inspection
        run: ls -la /root
      - name: Link ~/common-lisp
        run: ln -s /root/common-lisp /github/home/common-lisp
      - name: test-nothing
        env:
          STING_SYSTEMS: :alexandria
        run: sting
