name: Lisp application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: letrov/sting:test
    steps:
      - uses: actions/checkout@v1
      - name: sting
        env:
          STING_SYSTEMS: :alexandria
          HOME: /
        run: sting
